site_name: Zeng's notebook
site_url: https://zhz235.github.io/zhznote
repo_name: zhz235/zhznote
repo_url: https://github.com/zhz235/zhznote/
site_description: zhz的笔记本
copyright: Copyright &copy; 2024 <a href="https://github.com/zhz235"  target="_blank" rel="noopener">zhz235</a>
theme:
  name: material
  palette:
      # 日间模式
      - scheme: default
        # 主颜色
        # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
        primary: indigo
        # 链接等可交互元件的高亮色
        # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
        accent: orange
        toggle:
          # 图标
          icon: material/weather-night
          # 鼠标悬浮提示
          name: 切换至夜间模式
      # 夜间模式
      - scheme: slate
        primary: indigo
        accent: orange
        toggle:
          icon: material/weather-sunny
          name: 切换至日间模式
  features:
    # 页面底部上一页下一页
    - navigation.footer
    # 使用 Tab 来进行分类
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes
    # 打开 Tab 时左侧目录全部展开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.expand
    # 搜索输入一些字母时推荐补全整个单词
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # 搜索的关键词文章加入高亮
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight
    # 可以通过按钮复制代码
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    # [点击按钮跳转至 GitHub 修改 Markdown 源文件]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
    - content.code.annotate
    - navigation.tracking
  language: zh
  font:
    text: LXGW WenKai Screen
    code: JetBrains Mono
#图标和表情扩展
plugins:
  # [搜索功能]
  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  # 之前中文搜索是 Insider 的功能（https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/），现在好像已经是默认功能了，
  - search:
      lang:
        - zh
        - en
        - ja
  # [给单篇文章添加标签]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # https://squidfunk.github.io/mkdocs-material/plugins/tags/#meta.tags



markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols  #智能符号
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  

extra_javascript:
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



nav:
  - home: index.md
  - language:
    - C: language/_c.md
    - python: language/_python.md
    - matlab: language/_matlab.md
  - Computer Science:
    - FDS: 
      - FDS/index.md
      - 树: FDS/tree.md
      - 堆: FDS/heap.md
      - 并查集: FDS/disjointset.md
      - 图: FDS/graph.md
      - 排序: FDS/sort.md
      - 哈希: FDS/hash.md

  - system:
    - system1: system/system1.md
  - tools: 
    - git: tools/_git.md
